### ISSUE TITLE
No users after a delete

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-backoffice#219]
I deleted a dozen of unused users. It went good, then I went page 2 and wanted to delete other users.

At this time I was able to check the box of users I wanted to delete but the deleted button was frozen.

So I did reloaded the page, and now my "Security" tab is completely empty : 

![image](https://cloud.githubusercontent.com/assets/24288932/22967703/e14f347a-f367-11e6-9171-1589c316064f.png)

Same for profiles and roles.

When bypassing Kuzzle and fetching directly ElasticSearch on internal Kuzzle index : "host:9200/%25kuzzle/users/_search"

Elastisearch give me 74 hits.

**Comment by BaptisteKaliop** [comment]
Found the user that make the troubles.

I had an user with an ID but with an empty document.

**Comment by AnthonySendra** [comment]
Hello,

This error will be fixed in #240.

:warning: You not supposed to have a user with empty body. The `profileIds` attribute is mandatory. If you try to create user via Elasticsearch, you have to follow kuzzle specification. (is not a good idea to use directly Elasticsearch to manage the %kuzzle index)

**Comment by AnthonySendra** [comment]
Fixed in 2.1.0
